### ISSUE TITLE
Viewer submission, video direction

### ISSUE THREAD

**Issue by dclunde** [standupmaths/xmastree2021#21]
I really hope I didn't miss it in the video or these repos, but @thatmattparker what direction(s) will you be filming our visualizations from? I have a big idea, but will not make sense unless viewed from a specific direction.

You mention in the video that I believe the XZ plane is in frame currently, but will that still be so during the video?

Thanks!

**Comment by thatmattparker** [comment]
Yes, I will film looking directly down the positive x axis. Same as in my video. Which means the ‘viewing plane’ is YZ.

**Comment by dclunde** [comment]
@thatmattparker - Thanks so much! Stoked!

**Comment by jukindle** [comment]
@thatmattparker just to clarify, will the camera be located at a positive or negative x-coordinate (i.e. cam_x = 5 or cam_x = -5) in GIFT reference frame?

**Comment by dclunde** [comment]
oh, I'm also assuming there will be a secondary camera so we can see the 3D affects. Thanks!

**Comment by thatmattparker** [comment]
Just one camera at roughly cam_x = 5.

**Comment by oliverdunk** [comment]
Closing as answered by Matt :)
