### ISSUE TITLE
Brightness recommendations

### ISSUE THREAD

**Issue by connorf25** [standupmaths/xmastree2021#28]
Hi, saw this YouTube comment from suncrasher, which hasn't been addressed yet and I was wondering too:

> `Question regarding brightness: Last time you recommended to not go above (50, 50, 50) for large amounts of LEDs because (a) that was bright enough already and (b) your power supplies didn't manage more. Does that still apply?`

**Comment by thatmattparker** [comment]
Yes, I was running the spinning effects with a max of 50 per value but you could push to 100 if you're only using one colour (for whole-tree effects). I might try to have some control to scale brightness up or down if people's CSV effects are too bright/dim.

**Comment by d-albrecht** [comment]
I hope that would then be a global scaling for the whole animation and not individual frames, otherwise the effect might be ruined, ;) But my animations should be fine.

**Comment by thatmattparker** [comment]
Yes, it would be a blunt global scaling across the entire run of the effect. And only if the effect doesn’t display initially because the power supplies cannot keep up.

**Comment by rendermaniac** [comment]
I haven't taken a "tree gamut" into account at all - I have assumed 0-255 is available. Global scaling would work for me.

**Comment by oliverdunk** [comment]
Seems like Matt cleared this one up so closing for now :)
