### ISSUE TITLE
Examples folder doesn't actually exists

### ISSUE THREAD

**Issue by clarkwinkelmann** [standupmaths/xmastree2021#3]
The README says there's an example folder but it doesn't appear to actually be there.

> The `examples` folder has been created as a place for any effects contained within a single CSV file. Files should be named based on the effect - `fire.csv` for example.

Should the first PR create it, or did you intend to create the folder with an existing example file?

If the folder was completely empty it might have been ignored by git. It could be created with an empty `.gitkeep` file inside to force git to keep it.

I don't have anything to submit just yet but I wanted to point this out because I noticed it while reading the README.

**Comment by danielduarte-baird** [comment]
If you check the Xmas 2020 repo, you can access it there

**Comment by clarkwinkelmann** [comment]
Oh I didn't realize the README had been copy-pasted from last year!

Someone will still have to create it for this year I suppose, to make sure everyone puts their PRs in the right place :innocent: 

I hoped there would be at least one example file with the new format tested by Matt himself on his tree. The https://github.com/GSD6338/XmasTree repo doesn't have any demo specific to Matt's coordinates.

**Comment by oliverdunk** [comment]
Hey @clarkwinkelmann! I'm not sure if this was intentional or not, but creating the folder through the first PR we merge sounds fine to me. On examples of the format - I don't think anything exists right now but I'll pass the feedback along.

**Comment by Aonodensetsu** [comment]
I think the examples from GSD6338 are in the same format / using the same software that Matt is going to use? That would make the most sense since that is still getting updated slightly, for example to include timing information for animation playback.
