### ISSUE TITLE
Provide corrupt / original tree file

### ISSUE THREAD

**Issue by karlsve** [standupmaths/xmastree2021#41]
@thatmattparker As I would like to test my local code to fix a corrupted tree file with real data, and I personally don't have a setup to gather incorrect / incomplete data from, would it be possible to share the original file from this year thats not corrected?

My idea was that it should be possible to at least give the incorrectly positioned lights as an output and maybe even get them in line where they should be or at least roughly in that area, without scanning the tree again.

**Comment by d-albrecht** [comment]
I think you are looking for [this here](https://github.com/standupmaths/xmastree2021/blob/ca8f2b88213a1750b06c6e69f22280def777a76a/light_fixer.py#L2). They aren't normalized yet, but as far as I understand this, these are all LED positions in the "camera-pixel-count-format" (at which pixel in the camera images is the brightest point). Perhaps run them through some form of normalization first (or use them as is).

**Comment by karlsve** [comment]
I see, my bad, missed that line. Will have to put it through a normalizer build according to the specs given. -1 to 1 for x,y and the correct relative value for z. Makes comparison a lot easier. I think I should be able to do so, thanks for the hint again.

**Comment by karlsve** [comment]
To ease future use i created a Pull Request for the raw data in gift format #43. @d-albrecht
