### ISSUE TITLE
Power Supply Limitations

### ISSUE THREAD

**Issue by NicolasVargas11235** [standupmaths/xmastree2021#48]
Hello everyone. I was hoping to get some information on any possible LED brightness limits before submitting my files. I know that last year some programs were too demanding for the power supply, which caused issues with the animations. I also know the @thatmattparker has upgraded the power supply this time around, so I don't know if this is an issue anymore. 

For now, I have set my most demanding animation to have every LED always on with only one rgb color value of 100.

**Comment by d-albrecht** [comment]
You already closed this issue, so I guess you found the answer, but in case anyone else finds this and has the same question, [look here](https://github.com/standupmaths/xmastree2021/issues/28#issuecomment-1002987408),
