### ISSUE TITLE
Deadline for entries

### ISSUE THREAD

**Issue by rendermaniac** [standupmaths/xmastree2021#56]
Just wondering if there is an official cutoff point to receive entries by to make it into the video?

**Comment by NicolasVargas11235** [comment]
@rendermaniac if I remember correctly, @thatmattparker stated that entries should be submitted by January 9th either on GitHub or to matt+LEDs@standupmaths.com.

**Comment by rendermaniac** [comment]
Thanks! Clearly I need to listen properly!
