### ISSUE TITLE
Kind of quiet around here.

### ISSUE THREAD

**Issue by jtbowden** [standupmaths/xmastree2021#78]
The pull requests to this repo will be used in Matt's video, correct?  There was a lot of activity and questions about frame rate, etc, but now it has been very quiet.

**Comment by NicolasVargas11235** [comment]
My guess is they are busy setting up the actual event and are likely working on other events as well. @oliverdunk had mentioned that all files submitted by january 9 would be looked at and considered.

**Comment by oliverdunk** [comment]
Hey @jtbowden 👋  Yep, @thatmattparker is definitely going to include (or at least consider all of the) submissions from this repo. I need to find some time to test and merge things in bulk so apologies for the pause in activity!

**Comment by jukindle** [comment]
@thatmattparker did the project die?

**Comment by thatmattparker** [comment]
No, just been overly busy!

**Comment by jukindle** [comment]
@thatmattparker 🥲
